spring.application.name=email-good-sb
server.port=8081

# Gemini Config (currently getting 503 errors)
gemini.api.url=${GEMINI_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent}
gemini.api.key=${GEMINI_KEY:AIzaSyB2E-uC08uoeKVSZq1dG5ggSrhk6ktOLnU}

# Ollama Config (Local Setup)
# Ensure you have 'llama3.2:1b' pulled via `ollama run llama3.2:1b`
ollama.api.url=http://localhost:11434/api/generate
ollama.model=llama3.2:1b

# Toggle which AI provider to use ('ollama' or 'gemini')
ai.provider=ollama
